Error in <TFile::TFile>: file /lustre/scratch/samumcki/dSiPM_NN/mc_Simulation_run0_5_Test_1evt_pi+_5_5.root does not exist
Traceback (most recent call last):
  File "/lustre/work/samumcki/dSiPM_NN/tensorMaker.py", line 181, in <module>
    main()
  File "/lustre/work/samumcki/dSiPM_NN/tensorMaker.py", line 99, in main
    input_file = ROOT.TFile(input_file_path, "READ")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samumcki/miniconda3/lib/python3.12/site-packages/ROOT/_pythonization/_tfile.py", line 88, in _TFileConstructor
    raise OSError('Failed to open file {}'.format(args[0]))
OSError: Failed to open file mc_Simulation_run0_5_Test_1evt_pi+_5_5.root
mv: cannot stat 'tensor_0_5_pi+_5/npy/*': No such file or directory
slurmstepd: error: *** JOB 21827542 ON cpu-23-35 CANCELLED AT 2025-10-17T19:44:53 ***
